[package]
name = "compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utils = { path = "../utils" }
vm = { path = "../vm" }
unicode-xid = "0.2.0"

[features]
compiler_dev = []
